["Lucid Vision Labs-HTP003S-001-224500508"]
PixelFormat = "Mono16"
# AcquisitionFrameRateEnable = true
AcquisitionFrameRate = 100
Scan3dOperatingMode = "HighSpeedDistance625mmSingleFreq"
Scan3dAmplitudeGain = 1
ExposureTimeSelector = "Exp1000Us"
AcquisitionMode = "Continuous"
