[genicam.Basler]
PixelFormat = "Mono12"
AcquisitionMode = "Continuous"
BinningHorizontal = 2
BinningVertical = 2
ExposureTime = "2000"

[display.Basler.slider_defaults_min]
default_value = 0
min_value = 0
max_value = 4096


[display.Basler.slider_defaults_max]
default_value = 4096
min_value = 0
max_value = 4096