[genicam.Basler]
PixelFormat = "Mono8"
AcquisitionMode = "Continuous"
BinningHorizontal = 2
BinningVertical = 2
ExposureTime = "2000"

[display.Basler.slider_defaults_min]
default_value = 0
min_value = 0
max_value = 256


[display.Basler.slider_defaults_max]
default_value = 256
min_value = 0
max_value = 256