["Basler-267601741000-24383488"]
PixelFormat = "Mono8"
AcquisitionMode = "Continuous"
BinningHorizontal = 4
BinningVertical = 4
ExposureTime = 1000


["Basler-267601746219-24404505"]
PixelFormat = "Mono8"
AcquisitionMode = "Continuous"
BinningHorizontal = 4
BinningVertical = 4
ExposureTime = 1000


["Basler-267601746223-24404515"]
PixelFormat = "Mono8"
AcquisitionMode = "Continuous"
BinningHorizontal = 4
BinningVertical = 4
ExposureTime = 1000


["Basler-2676017611A4-24514980"]
PixelFormat = "Mono8"
AcquisitionMode = "Continuous"
BinningHorizontal = 4
BinningVertical = 4
ExposureTime = 1000
