[genicam]

[genicam.Lucid]
PixelFormat = "Coord3D_C16"
AcquisitionFrameRate = 110
AcquisitionFrameRateEnable = true
Scan3dOperatingMode = "HighSpeedDistance625mmSingleFreq"
ExposureTimeSelector = "Exp1000Us"
# TriggerOverlap = "Off"
# AcquisitionMode = "Continuous"
LineSelector = "Line3"
LineMode = "Input"
TriggerMode = "On"
TriggerSelector = "FrameStart"
TriggerSource = "Line3"
CounterSelector = "Counter0"
CounterEventSource = "Line3"
CounterEventActivation = "RisingEdge"
CounterTriggerSource = "AcquisitionStart"
CounterDuration = 10000000
CounterValue = 0
PtpEnable = true

[genicam."Lucid Vision Labs-HTP003S-001-223702048"]
TriggerDelay = 1200
CounterSelector = "Counter1"
CounterEventSource = "ExposureStart"
CounterEventActivation = "RisingEdge"
CounterTriggerSource = "AcquisitionStart"
CounterDuration = 10000000
CounterValue = 0
PtpSlaveOnly = false

[genicam."Lucid Vision Labs-HTP003S-001-224500508"]
TriggerDelay = 0
CounterSelector = "Counter1"
CounterEventSource = "ExposureStart"
CounterEventActivation = "RisingEdge"
CounterTriggerSource = "AcquisitionStart"
CounterDuration = 10000000
CounterValue = 0
PtpSlaveOnly = true

[display.Lucid.slider_defaults_min]
default_value = 900
min_value = 0
max_value = 5000


[display.Lucid.slider_defaults_max]
default_value = 1500
min_value = 0
max_value = 5000

