["genicam.Lucid Vision Labs-HTP003S-001-224500508"]
PixelFormat = "Mono16"
# AcquisitionFrameRateEnable = true
AcquisitionFrameRate = 100
Scan3dOperatingMode = "HighSpeedDistance625mmSingleFreq"
Scan3dAmplitudeGain = 1
ExposureTimeSelector = "Exp1000Us"
AcquisitionMode = "Continuous"


["display.Lucid Vision Labs-HTP003S-001-224500508.slider_defaults_min"]
default_value = 1800
min_value = 0
max_value = 5000


["display.Lucid Vision Labs-HTP003S-001-224500508.slider_defaults_max"]
default_value = 2200
min_value = 0
max_value = 5000

